---
name: "Build and Publish"
on:
  release:
    types:
      - released

jobs:
  release-build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/htyaml

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: build package
        run: uv build

      - name: publish package
        run: uv publish
